### ISSUE TITLE
Improve feedback when exiting a SW validator

### ISSUE THREAD

**Issue by VVander** [nodeset-org/hyperdrive#55]
![image](https://github.com/nodeset-org/hyperdrive/assets/6549498/cfc04a4e-b1a1-4891-bc26-ef8127f00743)

When exiting a validator normally, the exit message is displayed without a confirmation message. Instead, we should not display the exit message and simply indicate to the user that the validator has been entered into the exit queue successfully.

**Comment by VVander** [comment]
![image](https://github.com/nodeset-org/hyperdrive/assets/6549498/2ff097ac-4eab-46d6-b0da-704f202f1eed)

**Comment by jclapis** [comment]
Went ahead and did this in https://github.com/nodeset-org/hyperdrive/commit/e51e5d8c32d2dd48be3b09f7e52f3cba090f5660.
