### ISSUE TITLE
`hyperdrive stakewise validator exit` shows exit options even when there are no validators to exit

### ISSUE THREAD

**Issue by VVander** [nodeset-org/hyperdrive#60]
![image](https://github.com/nodeset-org/hyperdrive/assets/6549498/ebb43d5b-68ef-4c37-9fd4-bccc645f9985)

**Comment by jclapis** [comment]
Should be fixed in https://github.com/nodeset-org/hyperdrive/commit/e51e5d8c32d2dd48be3b09f7e52f3cba090f5660 which targets v0.3.0, you may or may not want to merge it in but I'm going to merge it into `nmc` anyway.
